# Generated by Django 6.0.1 on 2026-01-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='is_completed',
            new_name='profile_completed',
        ),
    ]
