# Generated by Django 6.0.1 on 2026-01-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_skills_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
