# Generated by Django 6.0.1 on 2026-01-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentprofile_graduation_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentskill',
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='studentskill',
            name='student',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='intrest',
            new_name='interest',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.DeleteModel(
            name='studentskill',
        ),
    ]
