# Generated by Django 6.0.1 on 2026-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentskill_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
